#!/bin/sh

usage() { echo "Usage: $0 [-f] [-h] [-q]" 1>&2; exit 1; }

while getopts ":fqh" o; do
    case "${o}" in
        f)
            f=1
            ;;
        q)
            q="-q"
            ;;
        h)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z ${f} ]
then
	echo this script will download and upgrade the overthebox with the last version
	read -p "Are you sure? [y/N]" -r REPLY
	if [[ "$REPLY" != "y" ]]
	then
	    exit 1
	fi
fi


URL_SOURCE=http://www.bruni68510.me/overthebox/
VERSION=
IMG_FILE=openwrt-brcm2708-bcm2709-rpi-2-b-ext4-sdcard.bin.gz

URL=$(uci get -q overthebox.me.image_url || echo "$URL_SOURCE/$VERSION/$IMG_FILE")

wget $URL -O /tmp/$IMG_FILE ${q}

sysupgrade /tmp/$IMG_FILE
